### ISSUE TITLE
Twitter token should not be placed in the repo

### ISSUE THREAD

**Issue by phy25** [huangluyang001/EC601-project#2]
This can be used to read/write your Twitter account. You can consult this help article from GitHub to clear it completely from the web (anyway, you need to reset these in Twitter developers website): https://help.github.com/articles/removing-sensitive-data-from-a-repository/

**Comment by huangluyang001** [comment]
Thank you for your advise. I have revised.

**Comment by phy25** [comment]
Again you should revoke your token or remove according to https://help.github.com/articles/removing-sensitive-data-from-a-repository/. The previous token can be easily seen: https://github.com/huangluyang001/EC601-project/commit/21bf6d05d87e4549aeebea59f81257f0b38651f3
